# Generated by Django 4.2.9 on 2024-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'user with this email address already exists'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
