# Generated by Django 4.2.9 on 2024-08-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
